### ISSUE TITLE
Issue with Blacklist token

### ISSUE THREAD

**Issue by chiragrc71** [nesso99/jwt-blacklist#1]
Using this package we only blacklist the token which has the expiration date.
But we can not Blacklist a token which has no expiration date
so, How to Blacklist a token which has no expiration date.

**Comment by nesso99** [comment]
Thank you for using my package. In my opinion, if you want to revoke a token without an expiration date, there will be a performance problem. You have some tokens in a blacklist forever and have to check them every time, so I suggest using a token with an expiration date in a common way. In my package, I temporarily give the maximum exp my package allow for the token without exp. Of course, I appreciate your question and will consider the better solution to improve the package.
