### ISSUE TITLE
Will it work with my use case?

### ISSUE THREAD

**Issue by shubham1164** [nesso99/jwt-blacklist#2]
I have a case, please let me know if I should use it or not?

I am working on a Mobile (Android/IOS) app with backend as Node.js for API.  I authenticate the user on mobile (via OTP on email) and then the user continue to login for lifetime. 
Now If the user lost his/her phone, then I must re-authenticate the user again (via OTP on email) on another phone. This should also logout from the previous (or lost) phone. 

Can I use your jwt-blacklist for my case? If yes, how much expiry time should I use for it?

**Comment by ghost** [comment]
In your case, you can show your users all unexpired tokens which he/she has (saving user token). By that way, the user can revoke any token they want as other apps do. My library is outdated and you can use Redis to revoke the token with expired time. I will update it soon. Thank you.

**Comment by shubham1164** [comment]
If I understand your solution correctly, user can revoke any token and if he found that his token is compromised he must revoke it. 

I am using [this](https://github.com/auth0/node-jsonwebtoken#readme) node library for generating/verifying the JWTs. But there is no doc explaining how to revoke it. Can you guide me?

**Comment by ghost** [comment]
The library doesn't have revoke function, this is the reason why this library was born.

**Comment by shubham1164** [comment]
ok I just want to understand the concept better in my use case. how to implement [this](https://github.com/auth0/node-jsonwebtoken#readme) library in my use case?

**Comment by shubham1164** [comment]
Can you recommend any other better way of solving the issue as of today?

**Comment by ghost** [comment]
you can use Redis to revoke token.

**Comment by shubham1164** [comment]
You mean by using Redis ( in-memory data storage) with blacklist feature?

**Comment by ghost** [comment]
you can save revoked token in Redis and check it when user login.

**Comment by shubham1164** [comment]
Thanks :)
